name: FAA Chart S3 Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup-s3:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      S3_BUCKET: faa-converted-charts-test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Delete all objects in S3 bucket
        run: |
          aws s3 rm s3://$S3_BUCKET --recursive
          echo "All objects deleted from $S3_BUCKET."
