name: FAA Charts Download, Convert & Upload

on:
  schedule:
    - cron: '0 6 * * 3'  # Every Wednesday at 06:00 UTC
    - cron: '0 6 * * 4'  # Every Thursday at 06:00 UTC
    - cron: '0 6 * * 5'  # Every Friday at 06:00 UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  download_convert_upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/..
    env:
      AWS_DEFAULT_REGION: us-east-1
      S3_BUCKET: faa-converted-charts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin python3-gdal unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install Python packages
        run: pip install -r FAATileConverter/requirements.txt

      - name: Run download and unzip script
        run: python FAATileConverter/scripts/download_faa_charts.py

      - name: Convert all GeoTIFFs to tiles
        run: python FAATileConverter/scripts/convert_faa_charts.py

      - name: Upload tiles to S3
        run: |
          set -euo pipefail
          echo "" > summary.txt
          for chart_type in sectional ifr_low ifr_high; do
            if [ -d "downloads/$chart_type" ]; then
              echo "Uploading $chart_type to S3"
              if aws s3 sync downloads/$chart_type s3://$S3_BUCKET/$chart_type --delete --only-show-errors; then
                echo "Successfully uploaded $chart_type to S3"
                echo "$chart_type uploaded" >> summary.txt
              else
                echo "Failed to upload $chart_type to S3" >&2
                echo "$chart_type FAILED" >> summary.txt
              fi
              echo ""
              echo ""
            else
              echo "No directory for $chart_type, skipping"
              echo "$chart_type missing" >> summary.txt
              echo ""
              echo ""
            fi
          done
        # summary.txt will be used for email notification

      - name: Upload logs if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: conversion-logs
          path: logs/

      - name: Upload summary artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary.txt

  notify_by_email:
    needs: download_convert_upload
    if: always()  # Run this even if previous job failed
    runs-on: ubuntu-latest
    steps:
      - name: Download summary artifact
        uses: actions/download-artifact@v4
        with:
          name: summary

      - name: Read summary.txt
        id: read_summary
        run: |
          SUMMARY_CONTENT="$(cat summary.txt)"
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with job status
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: FAA Charts Job - ${{ needs.download_convert_upload.result }}
          to: lightoreflight@gmail.com
          from: GitHub Actions <lightoreflight@gmail.com>
          body: |
            FAA Charts workflow run completed with status: ${{ needs.download_convert_upload.result }}

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Chart upload summary:
            ${{ steps.read_summary.outputs.summary }}
