name: FAA Charts Download, Convert & Upload

on:
  schedule:
    - cron: '0 6 * * 3'  # Every Wednesday at 06:00 UTC
    - cron: '0 6 * * 4'  # Every Thursday at 06:00 UTC
    - cron: '0 6 * * 5'  # Every Friday at 06:00 UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  download_convert_upload:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      S3_BUCKET: lightore-faa-charts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin python3-gdal unzip

      - name: Install AWS CLI
        run: pip install awscli

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run download and unzip script
        run: python scripts/convert_faa_charts.py

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          find downloads -type f

      - name: Convert all GeoTIFFs to tiles
        run: |
          set -euo pipefail
          shopt -s globstar

          for chart_type in sectional ifr_low ifr_high; do
            for tif in downloads/$chart_type/**/*.tif; do
              [ -e "$tif" ] || continue
              echo "Converting $tif to tiles"
              outdir="${tif%.tif}_tiles"
              if gdal2tiles.py -z 5-12 -w none "$tif" "$outdir"; then
                echo "Successfully converted $tif to $outdir"
              else
                echo "Failed to convert $tif" >&2
              fi
            done
          done

      - name: Upload tiles to S3
        run: |
          set -euo pipefail
          for chart_type in sectional ifr_low ifr_high; do
            if [ -d "downloads/$chart_type" ]; then
              echo "Uploading $chart_type to S3"
              if aws s3 sync downloads/$chart_type s3://$S3_BUCKET/$chart_type --delete --only-show-errors; then
                echo "Successfully uploaded $chart_type to S3"
              else
                echo "Failed to upload $chart_type to S3" >&2
              fi
            else
              echo "No directory for $chart_type, skipping"
            fi
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  notify_by_email:
    needs: download_convert_upload
    if: always()  # Run this even if previous job failed
    runs-on: ubuntu-latest
    steps:
      - name: Send email with job status
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: FAA Charts Job - ${{ needs.download_convert_upload.result }}
          to: lightoreflight@gmail.com
          from: GitHub Actions <lightoreflight@gmail.com>
          body: |
            FAA Charts workflow run completed with status: ${{ needs.download_convert_upload.result }}

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
